version: '3'

services:
  api:
    build: .
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development

  frontend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
