version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanastra-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'

  api:
    build: ./api
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanastra-db
      NODE_ENV: development
      MAILTRAP_HOST: sandbox.smtp.mailtrap.io
      MAILTRAP_PORT: 2525
      MAILTRAP_USERNAME: f978ef6b6c3123
      MAILTRAP_PASSWORD: 3b620b5e137bbf
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3434:3000'
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://api:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
