version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanastra-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'

  frontend:
    image: node:16.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:latest
    ports:
      - '3434:3000'
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - type: bind
        source: ./frontend/node_modules
        target: /app/node_modules

  backend:
    image: node:16.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
      cache_from:
        - node:latest
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanastra-db
      NODE_ENV: development
      MAILTRAP_HOST: sandbox.smtp.mailtrap.io
      MAILTRAP_PORT: 2525
      MAILTRAP_USERNAME: f978ef6b6c3123
      MAILTRAP_PASSWORD: 3b620b5e137bbf
    volumes:
      - ./api:/app
      - type: bind
        source: ./api/node_modules
        target: /app/node_modules
    depends_on:
      - postgres
